# Generated by Django 4.2.2 on 2024-09-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="ID чата Telegram"
            ),
        ),
    ]
