# Generated by Django 4.2.2 on 2024-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="дата привычки"),
        ),
    ]
