# Generated by Django 4.2.2 on 2024-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_habit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="date",
            field=models.DateField(default="2024-09-27", verbose_name="дата привычки"),
        ),
    ]
