# Generated by Django 4.2.2 on 2024-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0004_alter_habit_complete_time_alter_habit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Периодичность привычки в днях"
            ),
        ),
    ]
